spring.application.name=Votezy
spring.datasource.url=jdbc:mysql://localhost:3306/votezy_db
spring.datasource.username=root
spring.datasource.password=rayeesali@1510
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

